# Generated by Django 3.0.10 on 2020-10-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('breed', models.CharField(blank=True, default=' ', max_length=20, null=True)),
                ('color', models.CharField(blank=True, default=' ', max_length=20, null=True)),
                ('age', models.IntegerField(default=' ')),
                ('gender', models.CharField(default='', max_length=10)),
                ('size', models.CharField(default='', max_length=15)),
                ('weight', models.CharField(default='', max_length=15)),
                ('adoption_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(default=' ', max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets.Category')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
