# Generated by Django 3.0.10 on 2020-10-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, upload_to='pets/%Y/%m/%d'),
        ),
    ]
