# Generated by Django 3.0.10 on 2020-11-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20201027_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
