# Generated by Django 2.2 on 2020-06-19 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agile_Con', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('attendee_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(default=' ', max_length=50, unique=True)),
                ('email', models.EmailField(default=' ', max_length=100)),
                ('cell_phone', models.CharField(default='402-000-0000', max_length=50, null=True)),
                ('first_name', models.CharField(default='', max_length=50, null=True)),
                ('last_name', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('presenter_id', models.CharField(default=' ', max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(default=' ', max_length=50)),
                ('email', models.EmailField(default=' ', max_length=100)),
                ('cell_phone', models.CharField(default='402-000-0000', max_length=50, null=True)),
                ('first_name', models.CharField(default='', max_length=50, null=True)),
                ('last_name', models.CharField(default='', max_length=50, null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='presenters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('presentation_id', models.CharField(default=' ', max_length=50, primary_key=True, serialize=False)),
                ('timeslot', models.CharField(default=' ', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_slots', models.DecimalField(decimal_places=0, default=50, max_digits=10)),
                ('number_of_slots_remaining', models.DecimalField(decimal_places=0, default=50, max_digits=10)),
                ('location', models.CharField(default=' ', max_length=50)),
                ('description', models.CharField(default=' ', max_length=200)),
                ('presenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='Agile_Con.Presenter')),
            ],
        ),
    ]
