# Generated by Django 2.2 on 2020-06-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agile_Con', '0002_attendee_presentation_presenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='Agile_Con.Attendee')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='Agile_Con.Presentation')),
            ],
        ),
    ]
